name: "Auto-deploy to Zaneops"
author: Fredkiss3
branding:
  icon: play
  color: blue
description: "Deploy to zaneops automatically on git push"
inputs:
  SERVICE_IMAGE:
    description: "The new image of the service to deploy"
    required: true
  DEPLOY_WEBHOOK_URL:
    description: "URL to deploy your service"
    required: true
  COMMIT_MESSAGE:
    description: "Optional commit message associated with the deployment"
    required: false
  EXTRA_HEADERS:
    description: "Optional extra headers to pass to all the requests encoded as JSON"
    required: false

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install packages and Deploy to zaneops
      shell: bash
      run: |
        bun install --frozen-lockfile
        bun run index.ts
      env:
        DEPLOY_WEBHOOK_URL: ${{ inputs.DEPLOY_WEBHOOK_URL }}
        COMMIT_MESSAGE: ${{ inputs.COMMIT_MESSAGE }}
        SERVICE_IMAGE: ${{ inputs.SERVICE_IMAGE }}
        EXTRA_HEADERS: ${{ inputs.EXTRA_HEADERS }}
