name: "Auto-deploy to Zaneops"
author: Fredkiss3
branding:
  icon: play
  color: blue
description: "Deploy to zaneops automatically on git push"
inputs:
  username:
    description: "Username on ZaneOps dashboard"
    required: true
  password:
    description: "Password on ZaneOps dashboard"
    required: true
  project-slug:
    description: "Slug of the project that contains the service to be deployed."
    required: true
  service-slug:
    description: "Slug of the service to be deployed."
    required: true
  service-new-image:
    description: "The new image of the service to deploy"
    required: true
  base-url:
    description: "URL where the dashboard for zaneops is available"
    required: true
  commit-message:
    description: "Optional commit message associated with the deployment"
    required: false
  extra-headers:
    description: "Optional extra headers to pass to all the requests encoded as JSON"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
